apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsb-manager
  labels:
    app: dsb-manager
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dsb-manager
  template:
    metadata:
      labels:
        app: dsb-manager
    spec:
      volumes:
        - name: dsb-manager-volume
          persistentVolumeClaim:
            claimName: dsb-manager-pvc
        - name: dsb-manager-certs
          secret:
            secretName: dsb-manager-certs
      #securityContext:
      #  fsGroup: 5000
      containers:
      - name: dsb-manager
        image: "{{ .Values.dsbManager.image }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        {{ $ClusterVersion := index (lookup "config.openshift.io/v1" "ClusterVersion" "" "").items 0 "status" "desired" "version" }}
        {{ if or (contains "4.11" $ClusterVersion ) (contains "4.12" $ClusterVersion ) (contains "4.13" $ClusterVersion ) }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
        {{ end }}
        {{ if or (contains "4.9" $ClusterVersion) (contains "4.10" $ClusterVersion) }}
        {{ end }}
        volumeMounts:
        - mountPath: /opt/dsb/dsb-manager
          name: dsb-manager-volume
        - mountPath: /opt/dsb/dsb-manager/ssl
          name: dsb-manager-certs
        env:
          - name: MONGO_IP
            value: dsb-mongodb
          - name: MONGO_PORT
            value: {{ .Values.dsbMongodb.service.port | quote}}
          - name: MONGO_USER
            valueFrom:
              secretKeyRef:
                name: dsb-secret
                key: dsb-mongodb-username
          - name: MONGO_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dsb-secret
                key: dsb-mongodb-password
          - name: KEYSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dsb-secret
                key: dsb-keystore-password
          - name: CA_TRUSTSTORE_PASSWORD
            valueFrom:
              secretKeyRef:
                name: dsb-secret
                key: dsb-truststore-password
          - name: INIT_PASS
            valueFrom:
              secretKeyRef:
                name: dsb-secret
                key: dsb-initpass
          - name: KMS_CONFIG_PROPERTIES
            valueFrom:
              secretKeyRef:
                name: dsb-secret
                key: dsbCredstorePassword
          - name: SPRING_PROFILES_ACTIVE
            value: docker_prod
      imagePullSecrets:
      - name: {{ .Values.image.pullSecrets }}