apiVersion: batch/v1
kind: Job
metadata:
  name: labeller-remove
  annotations:
      "helm.sh/hook": "pre-delete"
      "helm.sh/hook-delete-policy": "hook-succeeded"
spec:
  template:
    spec:
      serviceAccountName: label-updater
      containers:
      - name: labeller
        image: icr.io/data-security-broker/labeller
        command: ["/bin/sh", "-c"]
        args:
          - |
            for node in $(kubectl get nodes -o=name); do
              node_name=$(echo $node | cut -d / -f 2)
              uuid=$(kubectl get configmap {{ .Values.dsbShield.configMap.name }} -o jsonpath='{.metadata.uid}' -n {{ .Release.Namespace }})
              kubectl label nodes $node_name dsb-shield-$uuid- || true
            done
      restartPolicy: Never
  backoffLimit: 4