apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: baffle-mongodb-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: standard
spec:
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
     storage: 2Gi

---
     
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
 name: baffle-manager-pvc
 annotations:
   volume.beta.kubernetes.io/storage-class: standard
spec:
 accessModes:
 - ReadWriteOnce
 resources:
   requests:
     storage: 2Gi
