apiVersion: v1
kind: Service
metadata:
  labels:
    app: baffle-shield-app2
  name: baffle-shield-app2
spec:
  ports:
  - port: 8444
    protocol: TCP
    targetPort: 8444
  selector:
    app: baffle-shield-app2
  type: LoadBalancer
