apiVersion: v1
kind: Secret
metadata:
  name: dsb-secret
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  {{- if .Release.IsInstall }}
  dsb-mongodb-username: {{ randAlphaNum 8 | b64enc | quote }}
  dsb-mongodb-password: {{ randAlphaNum 16 | b64enc | quote }}
  dsb-initpass: {{ required "initPass is required and must be a non-empty string. " .Values.secrets.initPass | b64enc | quote }}
  dsbCredstorePassword: {{ tpl ("{'kmsType': 'local', 'baffle_secret': '{{ required \"credstorePass is required and must be a non-empty string.\" .Values.secrets.credstorePass }}'}") . | b64enc }}
  {{- else }}
  dsb-mongodb-username: {{ index (lookup "v1" "Secret" .Release.Namespace "dsb-secret").data "dsb-mongodb-username" }}
  dsb-mongodb-password: {{ index (lookup "v1" "Secret" .Release.Namespace "dsb-secret").data "dsb-mongodb-password" }}
  dsbCredstorePassword: {{ index (lookup "v1" "Secret" .Release.Namespace "dsb-secret").data "dsbCredstorePassword" }}
  {{- end }}
  dsb-keystore-password: {{ required "keystorePass is required. Set the value to 'a2V5c3RvcmU=' " .Values.secrets.keystorePass }}
  dsb-truststore-password: {{ required "keystorePass is required. Set the value to 'Y2hhbmdlaXQ=' " .Values.secrets.truststorePass }}