apiVersion: apps/v1
kind: Deployment
metadata:
  name: dsb-web
  labels:
    app: dsb-web
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: dsb-web
  template:
    metadata:
      labels:
        app: dsb-web
    spec:
      securityContext:
        fsGroup: 5000
        runAsUser: 5000
      containers:
      - name: dsb-web
        image: "{{ .Values.dsbWeb.image }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          capabilities:
            drop: ["ALL"]
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets:
      - name: {{ .Values.image.pullSecrets }}
