apiVersion: v1
kind: Service
metadata:
  labels:
    app: dsb-mongodb
  name: dsb-mongodb
spec:
  ports:
  - port: {{ .Values.dsbMongodb.service.port }}
    protocol: TCP
    targetPort: 27017
  selector:
    app: dsb-mongodb
  type: {{ .Values.dsbMongodb.service.type }} 
