apiVersion: v1
kind: Service
metadata:
  labels:
    app: dsb-web
  name: dsb-web
spec:
  ports:
  - port: {{ .Values.dsbWeb.service.port }}
    protocol: TCP
    targetPort: 8080
  selector:
    app: dsb-web
  type: {{ .Values.dsbWeb.service.type }}
