apiVersion: v1
kind: Service
metadata:
  labels:
    app: dsb-manager
  name: dsb-manager
spec:
  ports:
  - port: {{ .Values.dsbManager.service.port }}
    protocol: TCP
    targetPort: 8553
  selector:
    app: dsb-manager
  type: {{ .Values.dsbManager.service.type }}
