apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-svc
  labels:
    app: {{ .Release.Name }}-svc
spec:
  ports:
  - port: {{ .Values.dsbShield.service.port }}
    protocol: TCP
    targetPort: 8444
  selector:
    app: {{ .Release.Name }}
  type: {{ .Values.dsbShield.service.type }}
