apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  BM_IP: {{ .Values.dsbShield.configMap.data.BM_IP}}
  BM_SHIELD_SYNC_ID: {{ .Values.dsbShield.configMap.data.BM_SHIELD_SYNC_ID | quote }}
  BM_SHIELD_TAG: {{ .Release.Name | quote }}
  BS_SSL: {{ .Values.dsbShield.configMap.data.BS_SSL | quote }}
  BS_SSL_KEYSTORE_FILE: {{ .Values.dsbShield.configMap.data.BS_SSL_KEYSTORE_FILE | quote }}
  BS_SSL_KEYSTORE_PASSWORD: {{ .Values.dsbShield.configMap.data.BS_SSL_KEYSTORE_PASSWORD | quote }}
  BS_SSL_TRUSTSTORE_FILE: {{ .Values.dsbShield.configMap.data.BS_SSL_TRUSTSTORE_FILE | quote }}
  BS_SSL_TRUSTSTORE_PASSWORD: {{ .Values.dsbShield.configMap.data.BS_SSL_TRUSTSTORE_PASSWORD | quote }}
  BS_SSL_TLS_VERSION: {{ .Values.dsbShield.configMap.data.BS_SSL_TLS_VERSION | quote }}
  BM_MTLS: {{ .Values.dsbShield.configMap.data.BM_MTLS | quote }}
  BM_MTLS_CLIENT_CERT_PATH: {{ .Values.dsbShield.configMap.data.BM_MTLS_CLIENT_CERT_PATH | quote }}
  BM_MTLS_CLIENT_KEY_PATH: {{ .Values.dsbShield.configMap.data.BM_MTLS_CLIENT_KEY_PATH | quote }}
  BM_MTLS_CA_CERT_PATH: {{ .Values.dsbShield.configMap.data.BM_MTLS_CA_CERT_PATH | quote }}
  BM_MTLS_KEYSTORE_PASSWORD: {{ .Values.dsbShield.configMap.data.BM_MTLS_KEYSTORE_PASSWORD | quote }}
  JAVA_ARGS: {{ .Values.dsbShield.configMap.data.JAVA_ARGS | quote }}