{{- $dsbca := genCA "dsb-ca" 1825 -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dsb-ca
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  dsbca.crt: {{ $dsbca.Cert | b64enc }}
  dsbca.key: {{ $dsbca.Key | b64enc }}

---

{{- $dsbmanagercert := genSignedCert "example.com" nil nil 1825 $dsbca -}}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: dsb-manager-certs
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  dsbmanager.crt: {{ $dsbmanagercert.Cert | b64enc }}
  dsbmanager.key: {{ $dsbmanagercert.Key | b64enc }}
